### ISSUE TITLE
Doesn't seem to work with go test output

### ISSUE THREAD

**Issue by whipshock** [fatih/color#100]
I tried using this within a go test function and was not able to get the color in the terminal. It works within a regular main() function.
```
func Test_Color(t *testing.T) {
	color.Set(color.FgWhite, color.Bold)
	color.Cyan("Prints text in cyan.")
	fmt.Println("This is white in color")
}
```

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.

**Comment by vanta** [comment]
I've faced it today, any chance it can be fixed? I see you still maintain this project @fatih (PRs are being merged)?

**Comment by fatih** [comment]
Hi folks. Yeah I guess this one got slipped through my archived projects, and yes I'm maintaining this actively. This is really an old issue, so would appreciate to open a new one, with a reproducable case, what you're expecting. Of top of my mind comes that the Testing packages changes the stdout/stderr pipes, so maybe you have to explicitly set that inside the color package. Again would appreciate if you could open a new issue with a reproducible case.
