### ISSUE TITLE
Using color with multiwrater

### ISSUE THREAD

**Issue by 2gracia** [fatih/color#101]
Hello Fatih!
i am using code like this 
`
 code:

	mw := io.MultiWriter(os.Stdout, file)
	Trace = log.New(file,
		"TRACE: ",
		log.Ldate|log.Ltime|log.Lshortfile)
	
	Trace.SetOutput(mw)
`
Am I able  use your module in my code ?

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
