### ISSUE TITLE
API to convert text to ascii color but not print

### ISSUE THREAD

**Issue by ORESoftware** [fatih/color#110]
I didn't expect this to print the text:

```golang
color.Cyan("Prints text in cyan.")
```

instead I am looking for an API that does this:

```golang
log.Println(color.Cyan("text in cyan"))
```

where can I find this API?

**Comment by MarvinJWendt** [comment]
I think this is what you want: https://github.com/fatih/color#insert-into-noncolor-strings-sprintfunc

**Comment by ORESoftware** [comment]
thanks yeah this worked for me: https://github.com/logrusorgru/aurora
