### ISSUE TITLE
Is there a way to clear the set color string？

### ISSUE THREAD

**Issue by Like0x** [fatih/color#111]
Is there a way to clear the set color string?

I used color in other places, but I just want to clear the color in the specified place.

```go
Yellow = color.New(color.FgYellow).SprintFunc()
s := Yellow(str)
// clear color s ?
```

I don't want to turn  off the color globally.
```go
var flagNoColor = flag.Bool("no-color", false, "Disable color output")

if *flagNoColor {
	color.NoColor = true // disables colorized output
}
```

Is there any code to do that?

**Comment by fatih** [comment]
Yeah create your color instance first before using `SprintFunc()` and then you can disable it via `DisableColor()`, see: https://github.com/fatih/color#disableenable-color
