### ISSUE TITLE
Is fatih/color still actively maintained? 

### ISSUE THREAD

**Issue by iambenkay** [fatih/color#120]
This is a wonderful project and I would love to know if it is still actively maintained seeing that my issues were not replied to and my PR to it is gathering dust..

If it isn't being maintained anymore then I can push my updates to my fork instead and use that actively instead 🙂.

**Comment by bl-ue** [comment]
@iambenkay there's not many new features to add.  But @fatih merged fix PRs very fast. 😉

**Comment by eugene-manuilov** [comment]
@iambenkay @bl-ue no, it is not: https://github.com/fatih/color/issues/104#issuecomment-428767838

**Comment by bl-ue** [comment]
@eugene-manuilov that's very old, from 2018.  Since then, Fatih has been doing lots of maintenance such as merging PRs on this repository.
