### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by bjaglin** [fatih/color#13]
We have been using the library in https://github.com/michaelsauter/crane for a while, but a recent change you made (namely making `color.Set()` private) broke our build which does not use any vendoring mechanism. We worked around that with https://github.com/michaelsauter/crane/pull/187, but I am concerned about potential breaking changes in the future. Do you have any policy regarding backward-compatibility?

Thanks for your work!

**Comment by bjaglin** [comment]
Actually, I am checking out the `README.md`, and our use-case fall directly under https://github.com/fatih/color/blob/191595cfb2ec9522680470397712a174a5684bb5/README.md#plug-into-existing-code. It seems that the snippet there is broken in the same way, so maybe the underlying question is whether our work around is "fine"?

**Comment by fatih** [comment]
Hi @bjaglin 

I'm so sorry about the making it private. I'll change it to public. I never thought it was going to be used. This is imho wrong. As for versioning policy, I always try to keep my package's stable. If you check my other packages, that's always the case. This a human error and there was no test either testing this.

**Comment by bjaglin** [comment]
No worry! I thought maybe this was needed for the special case of Windows that seems to be worked on. Thanks!

**Comment by fatih** [comment]
Thanks for reporting @bjaglin. This is fixed now. If there is anything to do please let me know.
