### ISSUE TITLE
Panic when used on go 1.17

### ISSUE THREAD

**Issue by alekc** [fatih/color#147]
Hi, while using a terraform provider which list this project as one of it's dependencies I got a panic on the start of the process. After some digging turns out it's related to github.com/mattn/go-isatty v0.0.14

Dependabot has already bumped the version [here](https://github.com/fatih/color/commit/ab503e9325a87c026ea6540824e17f9b37ee4f65) but until there is a release it won't be fetched by the upstream. 

Can you have a look?

**Comment by fatih** [comment]
Hi @alekc 

Can you show me the panic output please? Or a sample example that makes fatih/color panic? 

Thank you

**Comment by alekc** [comment]
Probably better if I link directly the related PR https://github.com/mattn/go-isatty/pull/66 , also https://github.com/golang/go/issues/46645

**Comment by fatih** [comment]
Thank you @alekc I'll take a look at it.

**Comment by fatih** [comment]
It looks like go-isatty was already updated in go.mod, but I never released a new version. 

I just released a new version, `v1.13.0`, which now includes the latest updates.
