### ISSUE TITLE
Add branch tags to use with package managers like gopkg.in

### ISSUE THREAD

**Issue by nmabhinandan** [fatih/color#15]

**Comment by fatih** [comment]
Please use `godep` or any other package manager that supports vendor. There is currently only one branch and it's the master which is the stable one. Thanks for bringing this up.

**Comment by nmabhinandan** [comment]
Just add 0.1 or 1.0 branch tag something like https://github.com/codegangsta/negroni

**Comment by fatih** [comment]
Ok added: https://github.com/fatih/color/tree/v0.1
