### ISSUE TITLE
Broken escape codes on Windows 10 using cmd.exe

### ISSUE THREAD

**Issue by Integralist** [fatih/color#154]
👋🏻 

I'm testing the following code:

```go
package main

import (
	"fmt"
	"os"

	"github.com/fatih/color"
)

var Bold = color.New(color.Bold).SprintFunc()

func main() {
	s := fmt.Sprintf("Name: [%s] ", "default name")
	fmt.Fprint(os.Stdout, Bold(s))
}

```

On macOS the output is correctly bolded (as expected), while the output on Windows 10 cmd.exe displays:

```bash
←[1mName: [default name] ←[0m
```

I've noticed old issues like https://github.com/fatih/color/issues/91 where it mentions certain functions aren't supported by cmd.exe and so I'm not sure if there's a similar resolution here?

Any feedback/guidance appreciated.

Thanks.

**Comment by fatih** [comment]
Hi @Integralist 

If you use `color.Output`, it should work for both macOS and Windows:

```
fmt.Fprint(color.Output, Bold(s))
```

This makes sure to use the correct parser. You can also use the handy `Printxxx` methods of the colow, which use the correct stdout under the hood:

```
Bold.Print(s)
```

**Comment by Integralist** [comment]
Thanks I'll take a look at this 👍🏻

**Comment by Integralist** [comment]
@fatih Thanks for the feedback, this appears to work but I'm just noting for future travellers that I was initially still seeing an issue with escape codes being displayed rather than rendered.

For example, using your suggestion...

```go
fmt.Fprint(color.Output, Bold(s))
```

This printed fine on macOS but on Windows, although the text was 'bolded' I was seeing it prefixed with `←[0m`...

<img width="187" alt="Screenshot 2022-01-06 at 09 54 09" src="https://user-images.githubusercontent.com/180050/148364410-94cc8c45-cbf3-432e-ab4d-0bba7b7cb510.png">

Turns out this was because before that line I still had...

```go
fmt.Fprint(os.Stdout, Bold(s))
```

And so I'm guessing that was not closing off the ANSI escape code properly. So doing the following would make Windows render correctly...

```go
fmt.Fprint(os.Stdout, Bold(s))
fmt.Println("---")
fmt.Fprintf(color.Output, bold(s))
```

<img width="187" alt="Screenshot 2022-01-06 at 10 24 49" src="https://user-images.githubusercontent.com/180050/148368504-3d61c6ef-8681-45eb-8e9a-a22a563cd495.png">

**Comment by Integralist** [comment]
Oh! and for anyone using`os.Stderr`, the equivalent to use is `color.Error`.

**Comment by Hipska** [comment]
@fatih sorry to hijack this issue, but quick question, should [this](https://github.com/influxdata/telegraf/blob/6dc2b99549b3fc4684295ebcd2975cee96a1fa28/cmd/telegraf/telegraf.go#L270) be working on Windows?
