### ISSUE TITLE
Empty line added when filtering to 'less -R'

### ISSUE THREAD

**Issue by lyderic** [fatih/color#157]
This is a minimal program to reproduce the issue (I am on Ubuntu Linux 20.04 and I use gnome-terminal):

```go
package main

import "github.com/fatih/color"

func main() {
    red := color.New(color.FgRed)
    color.NoColor = false
    red.Println("foo")
}
```

When run, the above program displays _foo_ in red. Good.

However, when the output is piped to _less -FR_, an empty line is added:

```
$ go run main.go
foo
$ go run main.go | less -FR
foo
            <--- empty line here :-(
$ go run main.go | less -F
ESC[31mfoo
ESC[0m
```

Please note that in the output above, _foo_ on lines 2 and 4 is rendered in red on my screen. One can see that the raw line _ESC[0m_ is added at the end, which is not the desired output, I think.

The desired output would be:

```
$ go run main.go | less -F
ESC[31mfooESC[0m
```

Thanks for looking at it.

**Comment by fatih** [comment]
Hi @lyderic 

Thanks for the feedback. I know it's late, but I've opened a fix: https://github.com/fatih/color/pull/192 you can check it out yourselves as well.

**Comment by lyderic** [comment]
Many thanks for sorting this out!
L
