### ISSUE TITLE
Could not install in Golang 1.18

### ISSUE THREAD

**Issue by piqoni** [fatih/color#159]
Tried to install this package in GO 1.18 and go the following error. 

go install github.com/fatih/color@latest
**package github.com/fatih/color is not a main package**

Any suggestion? :)

**Comment by Gelio** [comment]
This is not an executable binary (which you install with `go install`) - this is a library package which you can install using `go get`. Citing the README:

```sh
go get github.com/fatih/color
```

I was able to install it on go 1.18 without any issues

**Comment by piqoni** [comment]
Thanks, that day I tried `go get` but got something like below, and had to move forward and I removed the library from my script:
![image](https://user-images.githubusercontent.com/3144671/160294448-5ee8c4b8-4240-4a86-9a6e-bc8ca3603392.png)

Not being familiar with the new golang changes, I did a `go mod init` and then a 'go get' (no error) but then when importing the package on my script just to try it out I get "import cycle not allowed"

![image](https://user-images.githubusercontent.com/3144671/160294566-714ad86d-2dcc-4422-b83b-8000ddc2e619.png)

**Comment by Gelio** [comment]
I'm afraid you will need to share more details for me to try to help you. It would be ideal if you could share reproduction steps (what steps do I need to take to get to the problem you're facing) or a repository that contains that problem.

I have tried setting up a new go module on go 1.18 and I was able to successfully use this library:

```sh
✔ ~/projects
09:09 $ mkdir color-test
✔ ~/projects
09:09 $ cd color-test
✔ ~/projects/color-test
09:09 $ go mod init github.com/Gelio/color-test
go: creating new go.mod: module github.com/Gelio/color-test
✔ ~/projects/color-test
09:09 $ go get github.com/fatih/color
go: added github.com/fatih/color v1.13.0
go: added github.com/mattn/go-colorable v0.1.9
go: added github.com/mattn/go-isatty v0.0.14
go: added golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c
✔ ~/projects/color-test
09:10 $ nvim main.go
✔ ~/projects/color-test
09:10 $ go run main.go
Colored output
✔ ~/projects/color-test
09:11 $ go version
go version go1.18 linux/amd64
09:13 $ cat main.go
package main

import (
        "fmt"

        "github.com/fatih/color"
)

func main() {
        fmt.Println("Colored", color.RedString("output"))
}
```

![image](https://user-images.githubusercontent.com/889383/160345393-c02432de-075b-477e-9a73-12991a58e073.png)

**Comment by AndyCyberSec** [comment]
simply it does not work

```
go get github.com/fatih/color
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```

**Comment by fatih** [comment]
> go: go.mod file not found in current directory or any parent directory.

It looks like you're trying to add a dependency to a Go project where you didn't create a go.mod file yet. You can create one via 

```
go mod init
```

and then us the `go get` file to add the color package to your `go.mod` file.

**Comment by vigo** [comment]
this issue should be closed... because it works :)
