### ISSUE TITLE
Request: Add uncolorize() function.

### ISSUE THREAD

**Issue by nmabhinandan** [fatih/color#16]
Once a color is set to a string there is no way to undo that. It is required while writing to file. So something like this would be great.
```go
func (c *Color) Uncolorize(str string) string {
// if str is colorized uncolorize it and return
}
```

**Comment by fatih** [comment]
There is `DisableColor()` and `EnableColor()` methods .Aren't they useful for you ? What's your case?

**Comment by nmabhinandan** [comment]
Those are different. If I create a colorized string like ` color.RedString("red text")` and then if I wrote it to the file, the text editors aren't parsing the string. It works with the `cat` command but the text editors like sublime text aren't parsing them correctly.

**Comment by Tonkpils** [comment]
I'm assuming you mean removing the formatting given to the string then? Not sure what you mean by 
>the text editors aren't parsing the string
