### ISSUE TITLE
Add the word "golang" to the repo description for searching

### ISSUE THREAD

**Issue by ooesili** [fatih/color#17]
When searching for "golang color" on GitHub, this repository is not listed. If I instead search for "go color", I do indeed find it.

I'd recommend doing something like [mitchellh/colorstring](https://github.com/mitchellh/colorstring), such as "Color package for Go (golang) http://godoc.org/github.com/fatih/color". I believe that this will make it easier for people to discover this repo.

**Comment by fatih** [comment]
Hi @ooesili, it's already added in the README.md :) Thanks for the suggestion though.

**Comment by ooesili** [comment]
I saw it in the README.md, but my point was that the GitHub search seems to only look through the title and description.

https://github.com/search?o=desc&q=golang+color&s=stars&type=Repositories&utf8=✓
https://github.com/search?o=desc&q=go+color&s=stars&type=Repositories&utf8=✓

**Comment by fatih** [comment]
Ah ok, I'll add it :+1:
