### ISSUE TITLE
Allow forcing color output

### ISSUE THREAD

**Issue by nabaco** [fatih/color#179]
As described in https://github.com/fatih/color#disableenable-color and can be seen in https://github.com/fatih/color/blob/main/color.go#L23, when piping the output no colors will be applied.
There are some usecases when the user might want the colors to persist even when piping (e.g. piping a command output to `less -R`).
Is it possible to add an option to force colors unconditionally?

**Comment by fatih** [comment]
If you explicitly set  `NoColor` to `false`, it will forcefully log with escape characters, so (it's `false` instead of `true`):

```go
if *flagForceColor {
	color.NoColor = false // force colorized output
}
```

Does this solve your issue?

**Comment by nabaco** [comment]
Confirmed as working, thanks.
