### ISSUE TITLE
using underline with a different fg color breaks it

### ISSUE THREAD

**Issue by Yakiyo** [fatih/color#206]
I'm trying to pretty print a markdown file. The file uses `{{ some-text }}` in it for indicating variables, im removing the `{{`/`}}` and underline the inner text, and i'm also making the entire line cyan. But it seems, cyan get's removed after the first occurrence of the underlined word.
An example image:
![image](https://github.com/fatih/color/assets/91675932/5b87e5e9-dd33-438a-a896-397e3bd57bfc)

The part of the code is somewhat like this
```go
var underline = color.New(color.Underline).Sprint

line = highLightVariable(line)
line = color.CyanString(line)
fmt.Println(line)

func highLightVariable(line string) string {
	lines := strings.Split(line, "}}")
	lines = lo.Map(lines, func(line string, _ int) string {
		l := strings.Split(line, "{{")
		if len(l) > 1 {
			l[1] = underline(l[1])
		}
		return strings.Join(l, "{{")
	})
	line = strings.Join(lines, "}}")
	line = strings.ReplaceAll(line, "{{", "")
	line = strings.ReplaceAll(line, "}}", "")
	return line
}
```
the cyan colors stops after the first underlined word, even tho consequent words to have underlines.

In case, the full code is needed, check [this](https://github.com/Yakiyo/tilde/blob/b900c4f990fac58bc90daa77c0f39039eeccc85f/render/format.go#L31)

**Comment by gregpoirson** [comment]
After the second format is applied (underline in your case), color appends a reset [0m.
see this example:
![image](https://github.com/fatih/color/assets/2430354/3a0a9757-873f-4142-b5f3-4c45e9f51c44)
and the corresponding raw text :
`[36mword1 word2  [1mword3[0m word4 [1mword5[0m[0m`

color should be reappling any other format set before the underline.

**Comment by gregpoirson** [comment]
Maybe instead of applying a generic reset [0m, color should apply the specific reset for the specified format.
for instance, to reset the underline [4m, color should use [24m. 
seems to me that the problem is in the unformat function (line 380)

**Comment by gregpoirson** [comment]
I will be submitting a branch 'issue_206' to resolve this issue.
