### ISSUE TITLE
Not Downloading

### ISSUE THREAD

**Issue by MCRealpvptr** [fatih/color#214]
I can't download on termux can someone help me

**Comment by fatih** [comment]
Please provide a more helpful message. What are you trying to do? What are you downloading? This issue doesn't make sense. I'll keep it open for a few days, if you don't provide them, I'll be closing it. Thank you.

**Comment by MCRealpvptr** [comment]
I fixed with that command 

****go mod init my-module****

And can you update readme.md 

go get change with go install because I through I have to use a go get

**Comment by fatih** [comment]
Closing this as it's relevant to the color package.
