### ISSUE TITLE
This package isn't working in OS X 10.11

### ISSUE THREAD

**Issue by marksalpeter** [fatih/color#23]
I checked the terminal settings. ANSI colors are enabled, and other terminal utilities (bower specifically) seem to be outputting colors correctly. I've tested with SprintFunc and color.Cyan(). Nothing seems to be outputting color.

**Comment by fatih** [comment]
Hi @marksalpeter. Is 10.11 out yet?

**Comment by Unknwon** [comment]
Any updates on this?

**Comment by fatih** [comment]
I don't know still what the problem is. It's working here right now and I can see the colors (I'm using the latest MAC OS X version btw). Can you give me more detail what's not working?

**Comment by Unknwon** [comment]
@fatih :trollface: I just noticed it may be a problem for me if it's a common issue before starting using, thanks!

**Comment by fatih** [comment]
I don't see any value in this Issue as it's just working for me and I don't see a reason it should be break for 10.11 as it works for me already.
