### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by petercolberg** [fatih/color#28]
Please use semantic versioning:

- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- https://wiki.debian.org/UpstreamGuide#Releases_and_Versions

**Comment by fatih** [comment]
Hi @petercolberg 

The package is already in good shape and v1.0. How exactly do you want me to tag it? How do you guys distribute go packages in debian? Let me know please. Thanks

**Comment by petercolberg** [comment]
Hi @fatih, thanks for considering to tag releases!

Debian packages each Go package repository as a separate Debian source package. In this case, your package has been [included in Debian](https://packages.debian.org/sid/golang-github-fatih-color-dev) as a dependency of [acmetool](https://github.com/hlandau/acme). The version of a Debian package includes an upstream part (e.g. "1.0.0") and a Debian part (e.g. "-1"). If an upstream author does not tag releases, we need to make up an upstream version number based on the git commit and date, which yields unwieldy versions that are cumbersome to compare. 

Tagged releases yield handy Debian package versions and make it easy to automatically [notice new upstream releases](https://tracker.debian.org/pkg/golang-gopkg-tylerb-graceful.v1) using the Debian package tracker.

**Comment by petercolberg** [comment]
You start with a `v1.0.0` tag. Whenever you wish to make a bug-fix release, you bump the patch version, for example to `v1.0.1`. When you add new functions, you bump the minor version, to `v1.1.0`. When you wish to break backwards compatibility, you bump the major version, to `v2.0.0`.

This allows your users to select a major version by importing the package as `gopkg.in/fatih/color.v1`. The [gopkg.in](https://gopkg.in) redirection service will fetch the latest tag `v1.Y.Z` matching the given major version `v1`.

**Comment by jredville** [comment]
This would also be useful for anyone using Glide to manage dependencies. I see that you have a v0.1 tag, but that is over a year old, so tagging would be helpful for us too.

Thanks

**Comment by fatih** [comment]
Is a tag like `v0.2.0` good as well ? I don't want to start with a major `1`. I've already created the tag: https://github.com/fatih/color/releases/tag/v0.2.0 let me know if this is not suitable and we can start with `v1.0.0`. Thanks

**Comment by petercolberg** [comment]
It’s really up to you as the author. If you decide to adopt semantic versioning, then versions < 1.0.0 mean “Anything may change at any time. The public API should not be considered stable.”, which is not very useful to downstream users. So yes, v1.0.0 would be nice; but take your time as you see fit.

**Comment by fatih** [comment]
Alright we have now a `v1.0.0` release: https://github.com/fatih/color/releases/tag/v1.0.0. Thanks all for the comments.
