### ISSUE TITLE
Latest version linking to go-colorable/go-isatty failing in Windows 10

### ISSUE THREAD

**Issue by pathaugen** [fatih/color#32]
Windows 10 usage of color that utilizes go-colorable/go-isatty is failing in Windows 10.

`fmt.Print(color.RedString("This is a test of Color"))`

![color-fail](https://cloud.githubusercontent.com/assets/8743911/16300626/bc4cd2fe-38f5-11e6-9385-5166ed898c02.PNG)

**Comment by fatih** [comment]
Hi @pathaugen,

Does it also fail if you just use the https://github.com/mattn/go-colorable package? If yes you should open an issue there, if not let me know please. The color package is fully ANSI compatible, so it should just works if `go-colorable` works as well (which was btw)

**Comment by pathaugen** [comment]
If another package is preventing yours from working I'll point this out:

We moved to:
https://github.com/shiena/ansicolor

Fully ANSI compatible as you state color is supposed to be.

Now everything works with ansicolor in Windows 10. It's a simple package for Windows coloring that doesn't have issues.

![color-fail-2](https://cloud.githubusercontent.com/assets/8743911/16323799/aca4ba0c-3962-11e6-9558-0f29f3afe0f5.PNG)

Using that package instead of go-colorable within your own, or using the solution they implement in their code which works for Windows 10 full ANSI would solve the issue, but either way the ANSI compatibility isn't working for Windows 10 as you currently have it.

**Comment by fatih** [comment]
We were using it already, but then @mattn switched it to go-colorable to support 256 colors: https://github.com/fatih/color/pull/25

@mattn do you know what the problem here is ? I don't have a windows machine and can't validate the issue.

**Comment by pathaugen** [comment]
Switching from it may be when it broke for me.

Should note, you have to test in Windows 10 separate from pre-10 due to the changes to the windows console subsystem.

Here is an interesting read, to get some background beyond "Windows 10 is different"
http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-%28v1511%29-Console-Host-Enhancements

Either way, ansicolor works. Love color for non-Windows would like to see Windows polished up so hope this helps.

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/c1b4304fd6d68cad.png)

doesn't reproduce

**Comment by fatih** [comment]
Thanks @mattn for the validation. @pathaugen as you see above, it's working without any problem. Maybe you did something wrong, but as you see it just works.

**Comment by dshafik** [comment]
I have now been able to reproduce this. It depends on the terminal you're using:

- Cmder/ConEmu: Works fine, in Bash for Windows, Cmd.exe, and powershell.exe
- powershell.exe: Works fine, though some colors are not visible (like `Yellow`)
- cmd.exe: shows escape codes as per @pathaugen

**Comment by joegrasse** [comment]
@mattn @fatih @dshafik 
>powershell.exe: Works fine, though some colors are not visible (like Yellow)

On windows 10 powershell, I can get ```Yellow``` to show if I ```Bold``` it.
