### ISSUE TITLE
Disabling for unsupported terminals, pipes, etc.

### ISSUE THREAD

**Issue by prologic** [fatih/color#38]
Hi, I'm evaluating this package and I have a question around disabling colors easily if the detected terminal/output/pipe/etc doesn't support colors?

**Comment by fatih** [comment]
Yes, but you can always change the `Output` variable to your own custom writer if you wish.

**Comment by prologic** [comment]
I see; Thanks!

**Comment by fatih** [comment]
You're welcome. Feel free to open another issue if you have something in mind.
