### ISSUE TITLE
${Color}String tries to interpret percent signs

### ISSUE THREAD

**Issue by caffinatedmonkey** [fatih/color#45]
If you do:

    fmt.Println(color.RedString("%"))

This is printed (in red):

    %!(NOVERB)

This should be printed (in red):

    %

The wrong output is displayed even when `color.NoColor` is set to true.

**Comment by fatih** [comment]
Hi @caffinatedmonkey 

This was fixed with #35, do you use an older version? Please fetch latest master and try again. Thanks.
