### ISSUE TITLE
Module not working for go > 1.6

### ISSUE THREAD

**Issue by vodolaz095** [fatih/color#49]
I have opened the issue here
https://github.com/golang/go/issues/18277

It seems like for Go v > 1.6 when i install your module by `go get github.com/fatih/color` it later cannot be imported in file. For Go version 1.5 it works as expected

**Comment by fatih** [comment]
Hi @vodolaz095 

I think you have a local problem on your host. It works fine. Please provide more extensive information if you think there is a problem.

**Comment by vodolaz095** [comment]
thanks. this problem was arised by upgrading fedora linux from 23 to 24 version. This issue disappeared when i made clean install of fedora linux of 24 version from liveUSB drive.
