### ISSUE TITLE
Feature request: add Errorf and Errorffunc

### ISSUE THREAD

**Issue by kokizzu** [fatih/color#5]
add `Errorf` and `Errorffunc` as target to `fmt.Errorf`

**Comment by fatih** [comment]
Wow, totally missed this one :) Can you provide any use case for returning colored errors? It didn't make sense for me, because you cand do it already with `fmt.Errorf`, however I'm curious if I miss something here.

**Comment by fatih** [comment]
I think the API is stable enough and we don't need to extend anything. It's already easiy to populate a custom error. Thanks
