### ISSUE TITLE
Please tag v1.2.0

### ISSUE THREAD

**Issue by AlekSi** [fatih/color#56]
Not just `v1.2`, for better compatibility with vendoring tools.

**Comment by fatih** [comment]
Can we rename the existing one? And what's the difference between `v1.2` and `v1.2.0` ?

**Comment by AlekSi** [comment]
> Can we rename the existing one?

You can tag the same commit as `v1.2.0`. You should not rename or remove `v1.2` as this will break things for some people.

> And what's the difference between `v1.2` and `v1.2.0`?

Strictly speaking, `v1.2` is not a valid [SemVer version](http://semver.org).
Regular version scheme makes life easier for tools (vendoring, analytics ,etc.) authors and users.

Sorry if you think I'm too pedantic (you are probably right 😄).

**Comment by fatih** [comment]
Haha @AlekSi no :) I was just curios. Ok let me try to create a version. There is a new PR, once I've merge it I'll release a new version so no need to retag this one. Thanks!

**Comment by fatih** [comment]
We have a new tag now with `v1.3.0`. Thanks
