### ISSUE TITLE
it does't working on window7(64bit)

### ISSUE THREAD

**Issue by liyu4** [fatih/color#57]
I get wrong when run pure-go on windows.

package main  

import("github.com/fatih/color")

func main() {
      color.Red("we are red")
}

1: window7 64bit
2: git bash

output:
![image](https://cloud.githubusercontent.com/assets/5621417/22686003/7ada0234-ed5d-11e6-8f30-fef5ae22de37.png)

**Comment by fatih** [comment]
@mattn do you know what the problem might be ?

**Comment by mattn** [comment]
@liyu4 you use the command on cygwin or msys2 shell. it's not real command prompt. It's pseudo console. https://github.com/mattn/go-isatty is checking the handle of stdin is whether is tty or not. To recognize cygwin/msys console, go-isatty should check pipe name of handle. Fortunately, implementation is alredy exists.

https://github.com/k-takata/go-iscygpty

Adding new depenency effect is too big currently. fatih/color is depended on [458 packages](https://godoc.org/github.com/fatih/color?importers). go-isatty is depended on [139 packages](https://godoc.org/github.com/mattn/go-isatty?importers). So I will add new API to check both terminal using some of code from go-iscygpty. Few hours ago, I got agreement to use some of code for go-isatty from the author. Thanks @k-takata

**Comment by liyu4** [comment]
well ,thanks @mattn

**Comment by fatih** [comment]
that's awesome. Thanks a lot @mattn for the clarification. When do you think it would be included into go-isatty? I think we can close this when you finish it.

**Comment by mattn** [comment]
Will do soon https://github.com/mattn/go-isatty/issues/8

**Comment by mattn** [comment]
Please note that I will add new API `IsCygwinTerminal`. I don't want to break behavior of IsTerminal. So you must change `IsTerminal(fd)` to `IsTerminal(fd) || IsCygwinTerminal(fd)`.

**Comment by fatih** [comment]
Hm, than it would also break my code if the user doesn't have new go-isatty. Is it an interface? Maybe I can do a type check and run a function before checking it.

**Comment by mattn** [comment]
https://godoc.org/github.com/mattn/go-isatty

go-isatty can't add new feature without add new func at least.

**Comment by mattn** [comment]
https://github.com/mattn/go-isatty/pull/13

**Comment by mattn** [comment]
Now added IsCygwinTerminal.

**Comment by fatih** [comment]
Thanks @mattn, I'll check how I can integrate without breaking it for older version of color.

**Comment by mattn** [comment]
Most easy way to do it is put latest github.com/mattn/go-isatty into your vendor directory.

**Comment by fatih** [comment]
Hm yeah that would work, I was against vendoring though because `fatih/color` is a library as well. I only vendor if it's `main` package, say CLI or service. But I think this is the only option I can do for now.

**Comment by fatih** [comment]
Waiting for: https://github.com/mattn/go-isatty/pull/14 After that I need to re-vendor again the latest.

**Comment by fatih** [comment]
@liyu4 can you test please this PR: https://github.com/fatih/color/pull/61 and let me know if it works or not

**Comment by liyu4** [comment]
hm, hold on!

**Comment by liyu4** [comment]
@fatih  😫   it's still so

below is code run on window7:
![image](https://cloud.githubusercontent.com/assets/5621417/23057370/d28a8768-f52a-11e6-9320-227c92279c2d.png)

Run:
![image](https://cloud.githubusercontent.com/assets/5621417/23057397/f9e9cf6c-f52a-11e6-980e-3a533aff5eda.png)

**Comment by mattn** [comment]
try to `go run -x main.go`

**Comment by liyu4** [comment]
I have tried it like you say, but there is no effect.  

this is working.

![image](https://cloud.githubusercontent.com/assets/5621417/23058127/62307528-f52e-11e6-80eb-bbf0d64f8140.png)

**Comment by liyu4** [comment]
@fatih @mattn 
![image](https://cloud.githubusercontent.com/assets/5621417/23058152/9154598c-f52e-11e6-87c8-d178a16a4c64.png)

**Comment by fatih** [comment]
@liyu4 I've pushde another fix, can you please try again? I think it was due not OR'in it.

**Comment by liyu4** [comment]
@fatih  very pleasure!

**Comment by liyu4** [comment]
@fatih  😭    i add  below code to color.go
NoColor = os.Getenv("TERM") == "dumb" ||
		!isatty.IsTerminal(os.Stdout.Fd()) ||
		!isatty.IsCygwinTerminal(os.Stdout.Fd())

but it doesn't working!

**Comment by mattn** [comment]
Are you really trying fix-windows branch?

**Comment by fatih** [comment]
@liyu4 we pushed another fix, please try again. Unfortunately I don't have the environment to test, so I'm just doing what you and @mattn and @k-takata suggest

**Comment by mattn** [comment]
colors are disabled in last fix.

```
diff --git a/color.go b/color.go
index d9f6aa1..06097b4 100644
--- a/color.go
+++ b/color.go
@@ -18,8 +18,7 @@ var (
        // or not. This is a global option and affects all colors. For more control
        // over each color block use the methods DisableColor() individually.
        NoColor = os.Getenv("TERM") == "dumb" ||
-               !isatty.IsTerminal(os.Stdout.Fd()) ||
-               !isatty.IsCygwinTerminal(os.Stdout.Fd())
+               (!isatty.IsTerminal(os.Stdout.Fd()) || !isatty.IsCygwinTerminal(os.Stdout.Fd()))

        // Output defines the standard output of the print functions. By default
        // os.Stdout is used.
```
This should be

```go
    NoColor = os.Getenv("TERM") == "dumb" ||
        (!isatty.IsTerminal(os.Stdout.Fd()) && !isatty.IsCygwinTerminal(os.Stdout.Fd()))
```

**Comment by liyu4** [comment]
sorry!  I had checkout to fix-windows
![image](https://cloud.githubusercontent.com/assets/5621417/23059338/f843ab5c-f533-11e6-9b48-3d93424fdd71.png)

**Comment by liyu4** [comment]
@mattn  you're right,   
 NoColor = os.Getenv("TERM") == "dumb" ||
        (!isatty.IsTerminal(os.Stdout.Fd()) && !isatty.IsCygwinTerminal(os.Stdout.Fd()))
that's working in my terminal, thanks @mattn  @fatih 

![image](https://cloud.githubusercontent.com/assets/5621417/23059598/0f7b7790-f535-11e6-842e-3c68ddfa7c5e.png)
