### ISSUE TITLE
Background colors not clearing properly after newline

### ISSUE THREAD

**Issue by jbsmith7741** [fatih/color#58]
Background color don't properly clear if using Println or Printf
``` go
func TestLineClear(t *testing.T) {
	New(BgWhite).Printf("Printf - Solid white\n")
	fmt.Println("Line should be normal")
	fmt.Println()

	New(BgWhite).Println("Println - Solid white")
	fmt.Println("Line should be normal")
	fmt.Println()

	New(BgWhite).Print("Print - Solid white\n")
	fmt.Println("Line should be normal")
}
```

![screen shot 2017-02-13 at 2 09 29 pm](https://cloud.githubusercontent.com/assets/6434838/22903548/37b24fd2-f1f6-11e6-82a3-eec4d855d2bf.png)

**Comment by fatih** [comment]
I think it has to do with the terminal. This is how iterm2 shows it:

![screen shot 2017-02-14 at 2 07 30 am](https://cloud.githubusercontent.com/assets/438920/22907474/fd45a23e-f251-11e6-971b-24639e0b247e.png)

What terminal are you using? I think think this is caused by something else.

**Comment by jbsmith7741** [comment]
I'm using Terminal 2.7.1 (388) on a Macbook pro running Sierra 10.12.3
