### ISSUE TITLE
Force color

### ISSUE THREAD

**Issue by NeilRickards** [fatih/color#71]
Like the `color.NoColor` flag it would be good to have a global flag to force color output.

**use case**: Currently if I pipe the output to `less` the color is automatically disabled because it is not detected as a tty.  I would like to do something like `myApp --color | less -r`

**Comment by fatih** [comment]
Why not set it to `false`? It would mean color is enabled always.

**Comment by NeilRickards** [comment]
Set what to `false`?

**Comment by fatih** [comment]
`color.NoColor = false`

**Comment by NeilRickards** [comment]
Ah yes - that's working.  Thanks very much!  Closing ticket.
Might be worth adding to the README.
