### ISSUE TITLE
Does this package work good for windows 10 command propmpt?

### ISSUE THREAD

**Issue by andreGarvin** [fatih/color#78]
quick shout out to you for this amazing package this truly makes my cli tools look very colorful and amazing. Sadly there is a 'But', I tried using the compiled and executable binary of the `go build` and there some weird I am guessing unencoded symbols surrounding the words of text that is supposed to be colored.

EX:
```bash
[31merror cache:[0m run `cache --help` command to see how to use cache and what commands to use.
```

If you could help understand that or maybe find a way to fix it that would be coolio

**Comment by thezone51** [comment]
Not FULLY correct. Some features, like italic or underlined types wouldn't work cause... Cause it's windows, who needs them?

**Comment by andreGarvin** [comment]
Well I mostly need them. I was using this tool called commander works fine but when I used my command prompt it did. It work, I was using the `color.RedString`

**Comment by fatih** [comment]
can you please open an issue to https://github.com/mattn/go-colorable. Let me know if there is an issue on this package though. I don't use Windows and have little I can do here. Thanks!
