### ISSUE TITLE
Add styling support?

### ISSUE THREAD

**Issue by omeid** [fatih/color#8]
Hi

I know with a name like "color" almost anything else is out of scope but I was wondering if you would consider adding support for "bold", "faint", "Italic", and "Underline".

Or perhaps they can fit in into an standalone package?

**Comment by fatih** [comment]
You can use them already. http://godoc.org/github.com/fatih/color#Attribute Or do you mean something else?

**Comment by omeid** [comment]
Whops. No idea how I missed it.

**Comment by omeid** [comment]
On a second though, helper string functions like `StringCOLOR` would be helpful.
