### ISSUE TITLE
Support CI clis

### ISSUE THREAD

**Issue by rakyll** [fatih/color#80]
Colored output seems to be disabled because color package is not detecting the CI system CLIs. It looks like many is setting a `CI` env variable we can look for and enable colors on the known providers. Also see the reference at https://github.com/chalk/supports-color/blob/master/index.js#L66.

**Comment by broady** [comment]
Or provide some other env variable to force color output?

**Comment by fatih** [comment]
I can add it, need to be sure it's worth adding it (probably is for many). 

As @broady said, in `gotest` main function, you could do it with the following (as an example just for `travis`):

```
if os.Getenv("CI") == "Travis" {
	color.NoColor = false
}
```

**Comment by broady** [comment]
^ this looks like a better patch than doing it in `color`.

**Comment by rakyll** [comment]
Happy to apply the patch instead.

**Comment by fatih** [comment]
Nice. Closing this. I believe it's better not add anything necessary.
