### ISSUE TITLE
PrintlnFunc is not compatible to fmt.Println

### ISSUE THREAD

**Issue by jojomi** [fatih/color#81]
What do you think about `PrintlnFunc` returning a func compatible to `fmt.Println` regarding to the return params?

Something like this:

``` go
// PrintlnFunc returns a new function that prints the passed arguments as
// colorized with color.Println().
func (c *Color) PrintlnFunc() func(a ...interface{}) (int, error) {
	return func(a ...interface{}) (int, error) {
		return c.Println(a...)
	}
}```

**Comment by fatih** [comment]
This came up before if you search for the Closed PR's or issues. The problem is that this breaks the API and this package is right now imported by hundreds of other packages. It's like this now forever (until I release a breaking version, which I don't want to right now). Thanks
