### ISSUE TITLE
Attribute "Faint" is not faint on Windows (cmd.exe)

### ISSUE THREAD

**Issue by alankm** [fatih/color#82]
Hello. I've tried using the Faint attribute for normally coloured console output. On Linux it works as expected: text is greyer and harder to read. On windows surprisingly the opposite is true: FgWhite is greyer and harder to read than Faint is.

I'm not sure if I should report that issue here, or on mattn's go-colorable.

**Comment by fatih** [comment]
Can you please open it to mattn's go-colorable. I dont' have direct Windows support so there is little I can do. Let me know if that is an issue I need to look at. Thanks!
