### ISSUE TITLE
Add support for 256-color and truecolor escape codes

### ISSUE THREAD

**Issue by Calinou** [fatih/color#93]
I'd like to use 256 color or even [truecolor escape codes](https://gist.github.com/XVilka/8346728) to create nicer-looking CLI tools, but this library only seems to support the 16 traditional ANSI colors. As terminal support for truecolor is quite good by now (including on Windows 10, in my testing), it would be useful to see support for those escape codes.

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.

**Comment by o6uoq** [comment]
@fatih how was your sabbatical?
