### ISSUE TITLE
Migrate to vgo

### ISSUE THREAD

**Issue by freddy33** [fatih/color#98]
Here a pull request in case you'll want to use vgo.

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
